version: '3'

services:
  # infrastructure
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: sivdev_user
      POSTGRES_PASSWORD: sivdev_pass
    ports:
      - "9432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  # airflow
  webserver:
    build:
      context: .
    depends_on:
      - db
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://sivdev_user:sivdev_pass@db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./airflow/__init__.py:/usr/local/airflow/__init__.py
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: [ "airflow", "webserver" ]
  scheduler:
    build:
      context: .
    depends_on:
      - webserver
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://sivdev_user:sivdev_pass@db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./airflow/__init__.py:/usr/local/airflow/__init__.py
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
    command: [ "airflow", "scheduler" ]

volumes:
  pgdata:
